### ISSUE TITLE
Timeout scanning low cardinality unindexed column in large table

### ISSUE THREAD

**Issue by roy-moven** [Dataherald/dataherald#214]
When scanning a column to determine if it's low cardinality, DataHerald runs SQL:
```sql
SELECT DISTINCT col_name FROM table_name LIMIT 200;
```
That query does a full table scan if the column is low cardinality and not indexed, which times out on a large table. DataHerald catches the timeout as an error and assumes the column is not low cardinality.

**Comment by roy-moven** [comment]
For PostgreSQL at least we could avoid this and make scanning much faster by reading the query planner statistics from the `pg_stats` view:
```sql
SELECT n_distinct FROM pg_stats WHERE tablename = 'table_name' AND attname = 'col_name';
```
That query returns instantly regardless of the size of the table. Probably similar statistics are available in some other databases.

**Comment by roy-moven** [comment]
Is there any interest in making this change for PostgreSQL?

I could see a fair argument that if these columns aren't indexed then they shouldn't be treated as low-cardinality columns for query generation purposes anyway, but when running against a legacy database sometimes adding indexes isn't an option.

**Comment by jcjc712** [comment]
Hello,

You're absolutely correct. We do indeed have a ticket to enhance the cardinality logic, and we plan to implement an optimized solution for each database system. As you suggested, we should utilize 'pg_stats' specifically for Postgres.

If you're interested in contributing, please feel free to make these changes for Postgres and create a pull request (PR). Otherwise, rest assured that we will be making this change in the near future.

Best regards,

**Comment by roy-moven** [comment]
Thanks for the quick response! I may be able to contribute. Do you have any general guidance for what this code should look like, or how you'd like to architect database-specific code?

**Comment by ppmarkus** [comment]
Because the process of scanning a table does not occur often and scanning tables is nicely done in parallel asynchronously , it is not a show stopper. We have tables with almost a billion rows with low-cardinality columns that are not indexed (didn't make much sense to index) that do take a few minutes (enough to grab a coffee) but still the process doesn't crash.

This is the code that you're talking about I think using sqlalchemy.

```
try:
    cardinality_query = sqlalchemy.select([func.distinct(dynamic_meta_table.c[column["name"]])]).limit(200)
    cardinality = db_engine.engine.execute(cardinality_query).fetchall()
except Exception:
    return ColumnDetail(
        name=column["name"],
        data_type=str(column["type"]),
        low_cardinality=False,
    )

etc.,...
```

I wanted to ask what you mean by using `pg_stats` for PostgreSQL and how this would be implemented.
`pg_stats` is not compatible with other SQL flavours but there are basically equivalents.

**Comment by roy-moven** [comment]
[pg_stats](https://www.postgresql.org/docs/16/view-pg-stats.html) is a system view provided by PostgreSQL to access the query planner statistics. We would query it using the SQL I posted above. It will be PostgreSQL-specific of course. Hopefully I will be able to provide a PR soon.

**Comment by jcjc712** [comment]
@roy-moven Hello, I apologize for the delayed response. Our goal is to establish adapter classes for each supported database system to maintain clean and modular code. Since this marks our inaugural integration with Postgres, it's acceptable to implement a conditional statement. If the driver indicates that the database is Postgres, we should execute the pg_stats query; otherwise, we can maintain the current behavior.

You can add the logic in the method called `get_processed_column` in the [sqlalchemy.py](https://github.com/Dataherald/dataherald/blob/main/dataherald/db_scanner/sqlalchemy.py) file.

Use the next condition:
`if db_engine.engine.driver == 'psycopg2':
    <your logic>
`

To debug the code I use this line:
`import ipdb; ipdb.set_trace()`
and while the docker containers are running I execute this
`docker attach <app-container-id>`

Please let me know if you have any question.

**Comment by roy-moven** [comment]
Yep that was my plan. I'll try to quickly get something working and leave it to you to make the architecture elegant later.
